In [2]:
from eegdash import EEGDashDataset

/home/arielalves/Undergrad-Research-EEG-FM/Dataset-Preprocessing/.ds1-venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/home/arielalves/Undergrad-Research-EEG-FM/Dataset-Preprocessing/.ds1-venv/lib/python3.12/site-packages/braindecode/models/eegpt.py:497: FutureWarning: Montage name 'standard_1020' is deprecated and will be removed in MNE 1.14. Use 'colin27_1020' instead.
  montage = mne.channels.make_standard_montage("standard_1020")
/home/arielalves/Undergrad-Research-EEG-FM/Dataset-Preprocessing/.ds1-venv/lib/python3.12/site-packages/braindecode/models/eegpt.py:1452: FutureWarning: Montage name 'standard_1020' is deprecated and will be removed in MNE 1.14. Use 'colin27_1020' instead.
  montage = make_standard_montage("standard_1020")

In [ ]:
dataset = EEGDashDataset(cache_dir="./data", dataset='ds007169')
dataset.description

[09/24/26 13:30:42] INFO     Auto-corrected misrouted storage.base for dataset on007169:             ]8;id=10642780;file:///home/arielalves/Undergrad-Research-EEG-FM/Dataset-Preprocessing/.ds1-venv/lib/python3.12/site-packages/eegdash/dataset/dataset.py\dataset.py]8;;\:]8;id=10642781;file:///home/arielalves/Undergrad-Research-EEG-FM/Dataset-Preprocessing/.ds1-venv/lib/python3.12/site-packages/eegdash/dataset/dataset.py#561\561]8;;\
                             s3://nemar/on007169 -> s3://openneuro.org/ds007169

,subject,task,age,sex,handedness,analysis_included,data_quality_overall,session,run,gender
0,001,nback,26.0,F,R,true,pass,None,None,None
1,007,nback,25.0,F,R,true,pass,None,None,None
2,020,nback,31.0,M,R,true,pass,None,None,None
3,009,nback,23.0,M,R,true,pass,None,None,None
4,004,nback,18.0,F,R,true,pass,None,None,None
5,011,nback,21.0,M,L,true,pass,None,None,None
6,014,nback,31.0,M,R,true,pass,None,None,None
7,015,nback,21.0,F,R,true,pass,None,None,None
8,018,nback,24.0,M,L,true,pass,None,None,None
9,016,nback,29.0,M,R,true,pass,None,None,None
10,002,nback,28.0,M,R,true,pass,None,None,None
11,008,nback,23.0,M,R,true,pass,None,None,None
12,019,nback,30.0,M,R,true,pass,None,None,None
13,012,nback,28.0,M,R,true,pass,None,None,None
14,005,nback,22.0,F,L,true,pass,None,None,None
15,010,nback,27.0,F,R,true,pass,None,None,None
16,003,nback,31.0,M,R,true,pass,None,None,None
17,006,nback,48.0,M,R,true,pass,None,None,None

In [5]:
dataset = EEGDashDataset(cache_dir="./data", dataset='ds006923')
dataset.description

[09/24/26 13:32:30] INFO     Auto-corrected misrouted storage.base for dataset on006923:             ]8;id=10642792;file:///home/arielalves/Undergrad-Research-EEG-FM/Dataset-Preprocessing/.ds1-venv/lib/python3.12/site-packages/eegdash/dataset/dataset.py\dataset.py]8;;\:]8;id=10642793;file:///home/arielalves/Undergrad-Research-EEG-FM/Dataset-Preprocessing/.ds1-venv/lib/python3.12/site-packages/eegdash/dataset/dataset.py#561\561]8;;\
                             s3://nemar/on006923 -> s3://openneuro.org/ds006923

,subject,task,age,gender,subject_type,level_of_education,years_of_education,school_dropout,gang_member,domestic_violence,...,cocaine,session,run,sex,type_of_crime_1,recidivist,age_of_first_use,type_of_crime_2,type_of_crime_3,type_of_crime_4
0,2016cg,restingstate,15.0,Male,No Offender,Middle school,10.0,No,No,No,...,No,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN
1,2016cg,restingstate,15.0,Male,No Offender,Middle school,10.0,No,No,No,...,No,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN
2,1013sg,restingstate,17.0,Male,Offender,Basic secondary,6.0,Yes,No,No,...,Yes,None,None,None,Sexual_Abuse,No,8.0,NaN,NaN,NaN
3,1013sg,restingstate,17.0,Male,Offender,Basic secondary,6.0,Yes,No,No,...,Yes,None,None,None,Sexual_Abuse,No,8.0,NaN,NaN,NaN
4,2003cg,restingstate,18.0,Male,No Offender,Technical,11.0,No,No,No,...,No,None,None,None,NaN,NaN,14.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
275,1087sg2,restingstate,17.0,Male,Offender,Basic secondary,8.0,Yes,No,No,...,No,None,None,None,Sexual_Abuse,No,NaN,NaN,NaN,NaN
276,1044sg,restingstate,17.0,Male,Offender,Basic secondary,8.0,Yes,No,Yes,...,Yes,None,None,None,Illegal,Yes,15.0,Carrying_of_Weapons/Narcotics_Violence,NaN,NaN
277,1044sg,restingstate,17.0,Male,Offender,Basic secondary,8.0,Yes,No,Yes,...,Yes,None,None,None,Illegal,Yes,15.0,Carrying_of_Weapons/Narcotics_Violence,NaN,NaN
278,1103sg2,restingstate,18.0,Male,Offender,Basic secondary,7.0,Yes,No,Yes,...,Yes,None,None,None,Homicide,No,15.0,NaN,NaN,NaN
279,1103sg2,restingstate,18.0,Male,Offender,Basic secondary,7.0,Yes,No,Yes,...,Yes,None,None,None,Homicide,No,15.0,NaN,NaN,NaN

In [3]:
dataset = EEGDashDataset(cache_dir="./data", dataset='ds006866')
dataset.description

[09/24/26 13:35:10] INFO     Auto-corrected misrouted storage.base for dataset on006866:             ]8;id=1821668;file:///home/arielalves/Undergrad-Research-EEG-FM/Dataset-Preprocessing/.ds1-venv/lib/python3.12/site-packages/eegdash/dataset/dataset.py\dataset.py]8;;\:]8;id=1821669;file:///home/arielalves/Undergrad-Research-EEG-FM/Dataset-Preprocessing/.ds1-venv/lib/python3.12/site-packages/eegdash/dataset/dataset.py#561\561]8;;\
                             s3://nemar/on006866 -> s3://openneuro.org/ds006866

,subject,task,age,gender,ucla_r,lsas,cesd,erq_cr,set_shifting_cost,cerq_os,...,cerq_pu,cerq_kp,cerq_pp,cerq_sp,cerq_k,cerq_oi,sns,session,run,sex
0,098,EmotionProcessingandRegulationtask,31.0,2.0,42.0,70.0,23.0,22.0,48.941560,11.0,...,14.0,13.0,12.0,14.0,12.0,12.0,7.0,None,None,None
1,037,EmotionProcessingandRegulationtask,23.0,2.0,44.0,43.0,31.0,40.0,76.553006,17.0,...,16.0,16.0,12.0,11.0,11.0,9.0,10.0,None,None,None
2,001,EmotionProcessingandRegulationtask,29.0,2.0,59.0,35.0,17.0,30.0,155.742621,11.0,...,16.0,19.0,20.0,10.0,11.0,9.0,6.0,None,None,None
3,039,EmotionProcessingandRegulationtask,21.0,1.0,62.0,93.0,33.0,17.0,48.156863,15.0,...,6.0,14.0,11.0,12.0,14.0,11.0,11.0,None,None,None
4,007,EmotionProcessingandRegulationtask,26.0,2.0,61.0,36.0,44.0,30.0,77.244495,14.0,...,9.0,12.0,13.0,14.0,13.0,13.0,5.0,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
143,086,EmotionProcessingandRegulationtask,27.0,1.0,44.0,63.0,19.0,19.0,211.125709,12.0,...,10.0,11.0,11.0,7.0,15.0,12.0,22.0,None,None,None
144,006,EmotionProcessingandRegulationtask,21.0,1.0,66.0,102.0,24.0,8.0,99.510969,11.0,...,5.0,13.0,10.0,10.0,14.0,16.0,15.0,None,None,None
145,088,EmotionProcessingandRegulationtask,35.0,2.0,43.0,52.0,18.0,22.0,257.766734,16.0,...,12.0,15.0,14.0,16.0,9.0,9.0,19.0,None,None,None
146,140,EmotionProcessingandRegulationtask,26.0,1.0,27.0,32.0,7.0,30.0,155.496702,16.0,...,13.0,20.0,16.0,10.0,6.0,7.0,15.0,None,None,None
147,045,EmotionProcessingandRegulationtask,19.0,2.0,39.0,59.0,13.0,25.0,58.624994,13.0,...,13.0,19.0,18.0,13.0,4.0,7.0,14.0,None,None,None

# ds004019 - preteens obesity effect on arithmetic processing

- 64 subjects
- age, gender, bmi, performance

In [15]:
dataset = EEGDashDataset(cache_dir="./data", dataset='ds004019')
dataset.description

[09/24/26 13:46:13] INFO     Auto-corrected misrouted storage.base for dataset on004019:             ]8;id=1821728;file:///home/arielalves/Undergrad-Research-EEG-FM/Dataset-Preprocessing/.ds1-venv/lib/python3.12/site-packages/eegdash/dataset/dataset.py\dataset.py]8;;\:]8;id=1821729;file:///home/arielalves/Undergrad-Research-EEG-FM/Dataset-Preprocessing/.ds1-venv/lib/python3.12/site-packages/eegdash/dataset/dataset.py#561\561]8;;\
                             s3://nemar/on004019 -> s3://openneuro.org/ds004019

   subject  task   age gender    bmi   ws performance  session  run  sex
0       17  math   9.0      F  17.95  N-O           H      NaN  NaN  NaN
1       50  math   9.0      F  18.35  N-O           H      NaN  NaN  NaN
2       61  math   9.0      F  18.14  N-O           L      NaN  NaN  NaN
3       14  math  10.0      M  17.31  N-O           L      NaN  NaN  NaN
4       41  math   9.0      F  32.25    O           H      NaN  NaN  NaN
..     ...   ...   ...    ...    ...  ...         ...      ...  ...  ...
57      23  math   9.0      M  15.48  N-O           H      NaN  NaN  NaN
58      54  math   9.0      F  18.34  N-O           H      NaN  NaN  NaN
59      56  math  10.0      M  27.75    O           H      NaN  NaN  NaN
60      38  math   9.0      F  28.56    O           H      NaN  NaN  NaN
61      51  math  10.0      M  37.36    O           L      NaN  NaN  NaN

[62 rows x 10 columns]

In [16]:
dataset.datasets[0].raw

Downloading sub-17_task-math_eeg.set: 100%|██████████| 286M/286M [05:39<00:00, 884kB/s]
Downloading sub-17_task-math_channels.tsv: 100%|██████████| 2.04k/2.04k [00:00<00:00, 3.61kB/s]
Downloading sub-17_task-math_events.tsv: 100%|██████████| 4.36k/4.36k [00:00<00:00, 22.0kB/s]
Downloading sub-17_task-math_events.json: 100%|██████████| 693/693 [00:00<00:00, 4.03kB/s]
Downloading sub-17_task-math_electrodes.tsv: 100%|██████████| 2.33k/2.33k [00:00<00:00, 11.8kB/s]
Downloading sub-17_task-math_coordsystem.json: 100%|██████████| 99.0/99.0 [00:00<00:00, 521B/s]
Downloading sub-17_task-math_eeg.json: 100%|██████████| 1.94k/1.94k [00:00<00:00, 11.2kB/s]