In [1]:
from eegdash import EEGDashDataset

/home/arielalves/Undergrad-Research-EEG-FM/Models-Benchmarking/BrainOmni/.venv/lib/python3.12/site-packages/braindecode/models/eegpt.py:497: FutureWarning: Montage name 'standard_1020' is deprecated and will be removed in MNE 1.14. Use 'colin27_1020' instead.
  montage = mne.channels.make_standard_montage("standard_1020")
/home/arielalves/Undergrad-Research-EEG-FM/Models-Benchmarking/BrainOmni/.venv/lib/python3.12/site-packages/braindecode/models/eegpt.py:1452: FutureWarning: Montage name 'standard_1020' is deprecated and will be removed in MNE 1.14. Use 'colin27_1020' instead.
  montage = make_standard_montage("standard_1020")

# [ds006923](https://openneuro.org/datasets/ds006923/versions/1.0.1) - EEG of Juvenile Offenders

## Description

- 74 juvenile offenders (JO)
- 66 juvenile non-offender controls

## EEG Acquisition

- Electrodes: 128 channels (radial placement, 10-20 system reference)
- Additional channels: EOG, ECG recorded
- Sampling rate: 2048 Hz
- Online filtering: 0.1-100 Hz bandpass
- Setup:
    - Participants seated awake
    - Continuous monitoring for movements/sleep
    - Event markers via serial communication (paradigm triggers)

## Paradigms
- Resting State (RS):
    - Total duration: 12 minutes
    - Sequence:
        - 4 min alternating eyes closed/open (COCO: Closed-Open-Closed-Open)
        - 8 min eyes closed (excluded from current dataset)
- Segment trimming:
    - 5s post-event onset
    - 5s pre-event offset (to avoid transition artifacts)

## Preprocessing pipeline (not applied to dataset)

+ Visual inspection:
    - Raw data review using BDFreader
    - Identification of bad channels/artifacts
+ Downsampling: 2048 Hz → 128 Hz (resting-state data)
+ Rereferencing: Average reference (replaced failed earlobe reference)
+ Filtering:
    - Bandpass FIR: 1-40 Hz
    - High-pass: 1 Hz (0.5 Hz cutoff, 425 points)
    - Low-pass: 40 Hz (45 Hz cutoff, 45 points)
+ Artifact Removal:
    - Bad channel rejection:
        - Flat signals > 5s
        - SD > 4
        - Correlation < 0.8 with neighbors
    - ASR (Artifact Subspace Reconstruction)
    - ICA + ICLabel (components >90% non-brain removed)

## Features extraction

- PSD Calculation: Welch's method (50% overlap, Hamming window)
- Frequency bands:
    - Delta (δ): 1-4 Hz
    - Theta (θ): 4-8 Hz
    - Alpha (α): 8-13 Hz
    - Beta (β): 13-30 Hz
- Features per band/channel:
    - Mean Power
    - RMS of PSD
    - Standard Deviation
    - Minimum Power
    - Maximum Power
    - Skewness
    - Kurtosis
- Feature volume: 14,336 features/subject (4 bands × 128 channels × 4 segments × 7 features)

## Dataset EEGDash info

In [2]:
dataset = EEGDashDataset(cache_dir="./data", dataset='ds006923')
dataset

[09/30/26 14:03:12] INFO     Auto-corrected misrouted storage.base for dataset on006923:             ]8;id=3196425;file:///home/arielalves/Undergrad-Research-EEG-FM/Models-Benchmarking/BrainOmni/.venv/lib/python3.12/site-packages/eegdash/dataset/dataset.py\dataset.py]8;;\:]8;id=3196426;file:///home/arielalves/Undergrad-Research-EEG-FM/Models-Benchmarking/BrainOmni/.venv/lib/python3.12/site-packages/eegdash/dataset/dataset.py#561\561]8;;\
                             s3://nemar/on006923 -> s3://openneuro.org/ds006923

Downloading sub-2016cg_task-restingstate_acq-epochs_eeg.set:   0%|          | 0.00/13.0M [00:00<?, ?B/s]

Downloading sub-2016cg_electrodes.tsv:   0%|          | 0.00/3.94k [00:00<?, ?B/s]

Downloading sub-2016cg_coordsystem.json:   0%|          | 0.00/106 [00:00<?, ?B/s]

Downloading sub-2016cg_task-restingstate_acq-epochs_eeg.json:   0%|          | 0.00/1.37k [00:00<?, ?B/s]

[09/30/26 14:04:24] INFO     EEGLAB file contains epochs (trials > 1), loading via read_epochs_eeglab. ]8;id=3196433;file:///home/arielalves/Undergrad-Research-EEG-FM/Models-Benchmarking/BrainOmni/.venv/lib/python3.12/site-packages/eegdash/dataset/base.py\base.py]8;;\:]8;id=3196434;file:///home/arielalves/Undergrad-Research-EEG-FM/Models-Benchmarking/BrainOmni/.venv/lib/python3.12/site-packages/eegdash/dataset/base.py#1691\1691]8;;\

                    INFO     Loading EEGLAB epoch file via read_epochs_eeglab:                           ]8;id=3196441;file:///home/arielalves/Undergrad-Research-EEG-FM/Models-Benchmarking/BrainOmni/.venv/lib/python3.12/site-packages/eegdash/dataset/io.py\io.py]8;;\:]8;id=3196442;file:///home/arielalves/Undergrad-Research-EEG-FM/Models-Benchmarking/BrainOmni/.venv/lib/python3.12/site-packages/eegdash/dataset/io.py#1991\1991]8;;\
                             sub-2016cg_task-restingstate_acq-epochs_eeg.set

                    WARNING  Loaded EEGLAB epoch file as continuous raw:                                 ]8;id=3196448;file:///home/arielalves/Undergrad-Research-EEG-FM/Models-Benchmarking/BrainOmni/.venv/lib/python3.12/site-packages/eegdash/dataset/io.py\io.py]8;;\:]8;id=3196449;file:///home/arielalves/Undergrad-Research-EEG-FM/Models-Benchmarking/BrainOmni/.venv/lib/python3.12/site-packages/eegdash/dataset/io.py#2188\2188]8;;\
                             sub-2016cg_task-restingstate_acq-epochs_eeg.set (4 epochs x 128 ch x 6400
                             samples = 25600 total samples).

<BaseConcatDataset | 280 EEGDashRaw(s) | 17203200 total samples>
  Sfreq*: 128.0 Hz
  Channels*: 128 (128 EEG)
  Ch. names*: A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, ... (+118 more)
  Montage*: head
  Duration*: 200.0 s
  (* from first recording)
  Description: 280 recordings × 25 columns [subject, task, age, gender, subject_type, level_of_education, years_of_education, school_dropout, gang_member, domestic_violence, displaced_by_violence, socioeconomic_stratum, consumer_of_psychoactive_substances, alcohol, marijuana, cocaine, session, run, sex, type_of_crime_1, recidivist, age_of_first_use, type_of_crime_2, type_of_crime_3, type_of_crime_4]

In [3]:
dataset.description

,subject,task,age,gender,subject_type,level_of_education,years_of_education,school_dropout,gang_member,domestic_violence,...,cocaine,session,run,sex,type_of_crime_1,recidivist,age_of_first_use,type_of_crime_2,type_of_crime_3,type_of_crime_4
0,2016cg,restingstate,15.0,Male,No Offender,Middle school,10.0,No,No,No,...,No,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN
1,2016cg,restingstate,15.0,Male,No Offender,Middle school,10.0,No,No,No,...,No,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN
2,1013sg,restingstate,17.0,Male,Offender,Basic secondary,6.0,Yes,No,No,...,Yes,None,None,None,Sexual_Abuse,No,8.0,NaN,NaN,NaN
3,1013sg,restingstate,17.0,Male,Offender,Basic secondary,6.0,Yes,No,No,...,Yes,None,None,None,Sexual_Abuse,No,8.0,NaN,NaN,NaN
4,2003cg,restingstate,18.0,Male,No Offender,Technical,11.0,No,No,No,...,No,None,None,None,NaN,NaN,14.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
275,1087sg2,restingstate,17.0,Male,Offender,Basic secondary,8.0,Yes,No,No,...,No,None,None,None,Sexual_Abuse,No,NaN,NaN,NaN,NaN
276,1044sg,restingstate,17.0,Male,Offender,Basic secondary,8.0,Yes,No,Yes,...,Yes,None,None,None,Illegal,Yes,15.0,Carrying_of_Weapons/Narcotics_Violence,NaN,NaN
277,1044sg,restingstate,17.0,Male,Offender,Basic secondary,8.0,Yes,No,Yes,...,Yes,None,None,None,Illegal,Yes,15.0,Carrying_of_Weapons/Narcotics_Violence,NaN,NaN
278,1103sg2,restingstate,18.0,Male,Offender,Basic secondary,7.0,Yes,No,Yes,...,Yes,None,None,None,Homicide,No,15.0,NaN,NaN,NaN
279,1103sg2,restingstate,18.0,Male,Offender,Basic secondary,7.0,Yes,No,Yes,...,Yes,None,None,None,Homicide,No,15.0,NaN,NaN,NaN

# [ds006866](https://openneuro.org/datasets/ds006866/versions/1.0.0) - Emotion Processing and Regulation Task (Static Stimuli)

## EEG Data Acquisition

- EEG Cap: 64-channel QuickCap
- Sampling rate: 1000 Hz

## Recorded channels

FP1, FPZ, FP2, AF3, AF4, F7, F5, F3, F1, FZ, F2, F4, F6, F8, FT7, FC5, FC3, FC1, FCZ, FC2, FC4, FC6, FT8, T7, C5, C3, C1, CZ, C2, C4, C6, T8, M1, TP7, CP5, CP3, CP1, CPZ, CP2, CP4, CP6, TP8, M2, P7, P5, P3, P1, PZ, P2, P4, P6, P8, PO7, PO5, PO3, POZ, PO4, PO6, PO8, CB1, O1, OZ, O2, CB2

## Additional Sensors

- HEO (Horizontal EOG)
- VEO (Vertical EOG)
- EKG
- GSR/EDA

## EEG Preprocessing

- Band-pass filtering: 0.1–30 Hz (zero-phase Hamming-windowed FIR)
- Downsampling: 250 Hz
- Re-referencing: average mastoids (M1, M2)
- Automatic bad-channel rejection: clean_rawdata (autocorrelation = 0.8)
- ICA: runica algorithm
- Automatic component rejection: ADJUST and SASICA
- Spherical interpolation of removed channels
- Epoching: −200 to 5000 ms relative to stimulus onset
- Baseline correction: −200 ms pre-stimulus
- Artifact rejection: ±100 µV within 200 ms moving window (100 ms step)
- Condition averaging: using ERPLAB

## Dataset EEGDash info

In [ ]:
dataset = EEGDashDataset(cache_dir="./data", dataset='ds006866')
dataset

[09/30/26 12:04:11] INFO     Auto-corrected misrouted storage.base for dataset on006866:             ]8;id=15596263;file:///home/arielalves/Undergrad-Research-EEG-FM/Models-Benchmarking/BrainOmni/.venv/lib/python3.12/site-packages/eegdash/dataset/dataset.py\dataset.py]8;;\:]8;id=15596264;file:///home/arielalves/Undergrad-Research-EEG-FM/Models-Benchmarking/BrainOmni/.venv/lib/python3.12/site-packages/eegdash/dataset/dataset.py#561\561]8;;\
                             s3://nemar/on006866 -> s3://openneuro.org/ds006866

<BaseConcatDataset | 148 EEGDashRaw(s) | 444062728 total samples>
  Sfreq*: 1000.0 Hz
  Channels*: 69 (69 MISC)
  Ch. names*: FP1, FPZ, FP2, AF3, AF4, F7, F5, F3, F1, FZ, ... (+59 more)
  Montage*: head
  Duration*: 2642.6 s
  (* from first recording)
  Description: 148 recordings × 22 columns [subject, task, age, gender, ucla_r, lsas, cesd, erq_cr, set_shifting_cost, cerq_os, cerq_a, cerq_r, cerq_pu, cerq_kp, cerq_pp, cerq_sp, cerq_k, cerq_oi, sns, session, run, sex]

In [ ]:
dataset.description

[09/30/26 12:02:28] INFO     Auto-corrected misrouted storage.base for dataset on006866:             ]8;id=15596257;file:///home/arielalves/Undergrad-Research-EEG-FM/Models-Benchmarking/BrainOmni/.venv/lib/python3.12/site-packages/eegdash/dataset/dataset.py\dataset.py]8;;\:]8;id=15596258;file:///home/arielalves/Undergrad-Research-EEG-FM/Models-Benchmarking/BrainOmni/.venv/lib/python3.12/site-packages/eegdash/dataset/dataset.py#561\561]8;;\
                             s3://nemar/on006866 -> s3://openneuro.org/ds006866

,subject,task,age,gender,ucla_r,lsas,cesd,erq_cr,set_shifting_cost,cerq_os,...,cerq_pu,cerq_kp,cerq_pp,cerq_sp,cerq_k,cerq_oi,sns,session,run,sex
0,098,EmotionProcessingandRegulationtask,31.0,2.0,42.0,70.0,23.0,22.0,48.941560,11.0,...,14.0,13.0,12.0,14.0,12.0,12.0,7.0,None,None,None
1,037,EmotionProcessingandRegulationtask,23.0,2.0,44.0,43.0,31.0,40.0,76.553006,17.0,...,16.0,16.0,12.0,11.0,11.0,9.0,10.0,None,None,None
2,001,EmotionProcessingandRegulationtask,29.0,2.0,59.0,35.0,17.0,30.0,155.742621,11.0,...,16.0,19.0,20.0,10.0,11.0,9.0,6.0,None,None,None
3,039,EmotionProcessingandRegulationtask,21.0,1.0,62.0,93.0,33.0,17.0,48.156863,15.0,...,6.0,14.0,11.0,12.0,14.0,11.0,11.0,None,None,None
4,007,EmotionProcessingandRegulationtask,26.0,2.0,61.0,36.0,44.0,30.0,77.244495,14.0,...,9.0,12.0,13.0,14.0,13.0,13.0,5.0,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
143,086,EmotionProcessingandRegulationtask,27.0,1.0,44.0,63.0,19.0,19.0,211.125709,12.0,...,10.0,11.0,11.0,7.0,15.0,12.0,22.0,None,None,None
144,006,EmotionProcessingandRegulationtask,21.0,1.0,66.0,102.0,24.0,8.0,99.510969,11.0,...,5.0,13.0,10.0,10.0,14.0,16.0,15.0,None,None,None
145,088,EmotionProcessingandRegulationtask,35.0,2.0,43.0,52.0,18.0,22.0,257.766734,16.0,...,12.0,15.0,14.0,16.0,9.0,9.0,19.0,None,None,None
146,140,EmotionProcessingandRegulationtask,26.0,1.0,27.0,32.0,7.0,30.0,155.496702,16.0,...,13.0,20.0,16.0,10.0,6.0,7.0,15.0,None,None,None
147,045,EmotionProcessingandRegulationtask,19.0,2.0,39.0,59.0,13.0,25.0,58.624994,13.0,...,13.0,19.0,18.0,13.0,4.0,7.0,14.0,None,None,None

## My Preprocessing

- l_freq = 1
- h_freq = 40
- down_freq = 200
- bad_ch_tolerance = 0.15
- ransac = True
- ica = True
- window_size=512
- ref_channels=['M1', 'M2']

# ds004019 - preteens obesity effect on arithmetic processing

- 64 subjects
- age, gender, bmi, performance

In [ ]:
dataset = EEGDashDataset(cache_dir="./data", dataset='ds004019')
dataset

In [ ]:
dataset.description